version: '3'
services:
  server:
    container_name: 'my-server'
    restart: 'always'
    build: .
    ports:
      - "4000:3001"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: 'my-database'
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none

